services:
  pg_mobiles:
    image: postgres:17
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mobiles_data
    volumes:
      - "./mobiles_data:/var/lib/postgresql/data:rw"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 5s
      retries: 5
      
  pg-database:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
      
  ingest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app/data"
    depends_on:
      pg_mobiles:
        condition: service_healthy
    command: >
      --user=root
      --password=root
      --host=pg_mobiles
      --port=5432
      --db=mobiles_data
      --table_name=all_mobiles_data
